# Generated by Django 4.2.16 on 2024-12-10 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0002_role_alter_person_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'People'},
        ),
        migrations.AddField(
            model_name='group',
            name='core_competency_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_core_1', to='experiences.corecompetency'),
        ),
        migrations.AddField(
            model_name='group',
            name='core_competency_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_core_2', to='experiences.corecompetency'),
        ),
        migrations.AddField(
            model_name='group',
            name='core_competency_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_core_3', to='experiences.corecompetency'),
        ),
    ]
