# Generated by Django 4.2.16 on 2024-12-10 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("experiences", "0003_corecompetency_alter_person_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Participation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hours", models.PositiveIntegerField(blank=True, null=True)),
                ("special_recognition", models.TextField(blank=True, null=True)),
                ("years", models.JSONField(default=list)),
                ("elementary", models.BooleanField(default=False)),
                ("high", models.BooleanField(default=False)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="experiences.group",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="experiences.person",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="group",
            name="members",
        ),
        migrations.AddField(
            model_name="group",
            name="members",
            field=models.ManyToManyField(
                through="experiences.Participation", to="experiences.person"
            ),
        ),
    ]
