# Generated by Django 4.2.16 on 2025-02-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0004_participation_alter_group_members'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corecompetency',
            options={'verbose_name_plural': 'Core Competencies'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name_plural': 'Activity Groups'},
        ),
        migrations.AlterModelOptions(
            name='participation',
            options={'verbose_name_plural': 'All Activity Participation'},
        ),
        migrations.AddField(
            model_name='person',
            name='graduating_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
