# Generated by Django 4.2.16 on 2025-02-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0005_alter_corecompetency_options_alter_group_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pathways',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('core_competencies', models.ManyToManyField(to='experiences.corecompetency')),
                ('groups', models.ManyToManyField(to='experiences.group')),
            ],
            options={
                'verbose_name_plural': 'Pathways',
            },
        ),
        migrations.CreateModel(
            name='Badges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='badges/')),
                ('is_active', models.BooleanField(default=True)),
                ('core_competencies', models.ManyToManyField(to='experiences.corecompetency')),
            ],
            options={
                'verbose_name_plural': 'Badges',
            },
        ),
    ]
