# Generated by Django 4.2.16 on 2025-03-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0006_pathways_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Controls whether this item is visible to the public'),
        ),
        migrations.AddField(
            model_name='group',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='person',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Controls whether this item is visible to the public'),
        ),
        migrations.AddField(
            model_name='person',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
