# Generated by Django 4.2.16 on 2025-03-04 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0008_modelvisibilitysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Controls whether this item is visible to the public'),
        ),
        migrations.AddField(
            model_name='role',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people', to='experiences.role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='GuardianStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(help_text='e.g., Parent, Legal Guardian, Grandparent', max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this relationship is currently active')),
                ('notes', models.TextField(blank=True, help_text='Any additional notes about this relationship')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_relationships', to='experiences.person')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_relationships', to='experiences.person')),
            ],
            options={
                'verbose_name': 'Guardian-Student Relationship',
                'verbose_name_plural': 'Guardian-Student Relationships',
                'ordering': ['-date_added'],
                'unique_together': {('guardian', 'student')},
            },
        ),
        migrations.AddField(
            model_name='person',
            name='guardians',
            field=models.ManyToManyField(related_name='students', through='experiences.GuardianStudent', to='experiences.person'),
        ),
    ]
