# Generated by Django 4.2.16 on 2025-03-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0009_role_is_public_role_last_modified_alter_person_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badges',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/badges/'),
        ),
        migrations.AlterField(
            model_name='person',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/backgrounds/'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/logos/'),
        ),
    ]
